language: rust
rust:
  - stable
cache: rust

install:
  - cargo install wasm-pack
  - nvm install 'lts/*'
  - npm install
  - cargo build --verbose
  - wasm-pack --target nodejs

script:
  - cargo test --all --verbose
  - npm test
