language: rust
rust:
  - stable
cache: rust

install:
  - 'curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh'
  - nvm install 'lts/*'
  - npm install
  - cargo build --verbose
  - wasm-pack build --target nodejs

script:
  - cargo test --all --verbose
  - npm test
